version: '3.8'
name: "energizeswap_project"
services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - net1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: batteryswap-db:3308
    volumes:
      - ./backend:/app
    depends_on:
      - batteryswap-db
    networks:
      - net1

  batteryswap-db:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    volumes:
      - .db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: energize_swap_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    networks:
      - net1

networks:
  net1:
    driver: bridge

volumes:
  .db_data:
